### ISSUE TITLE
Extract mutation arguments params as a Js.t bag

### ISSUE THREAD

**Issue by grsabreu** [mhallin/graphql_ppx#12]
Thanks for the great lib.

I want to use this lib with an Apollo binding I did, but I can't extract the right types right away to call the `mutate` Apollo function. Currently, I still need to manually like:

```reason
module SignUpQuery = [%graphql
  {|
  mutation signUp($input: SignUpInput!) {
    signUp(input: $input) {
      error
      token
    }
  }
|}
];

let query = GraphQLTag.gql(SignUpQuery.query);

module Types = {
  type signUpInput = {
    .
    "password": string, "firstName": string, "lastName": string, "email": string
  };
  type signUp = {. "error": Js.null_undefined(string), "token": Js.null_undefined(string)};
  type error = {. "message": string};
  type data = {. "loading": Js.boolean, "error": error, "signUp": signUp};
};

type signUp = {
  error: option(string),
  token: option(string)
};

let convert = (signUp: Types.signUp) : signUp => {
  error: Js.Null_undefined.to_opt(signUp##error),
  token: Js.Null_undefined.to_opt(signUp##token)
};

type data = Types.data;

type input = Types.signUpInput;

type response = Js.Promise.t(signUp);

```

I wished something like this was possible:

```reason
module SignUpQuery = [%graphql
  {|
  mutation signUp($input: SignUpInput!) {
    signUp(input: $input) {
      error
      token
    }
  }
|}
];

let query = GraphQLTag.gql(SignUpQuery.query);

module Types = {
  type signUpInput = SignUpQuery.queryInputBag; /* Have this bag */
  type signUp = SignUpQuery.queryPayloadBag; /* And this one */
  type error = {. "message": string};
  type data = {. "loading": Js.boolean, "error": error, "signUp": signUp};
};

type signUp = {
  error: option(string),
  token: option(string)
};

let convertInputToJS = query.parseInputToJS; /* Would get OCaml record and convert to input type */
let convert = query.parseResponse;

type data = Types.data;

type input = Types.signUpInput;

type response = Js.Promise.t(signUp);
```

**Comment by mhallin** [comment]
Hello!

This PPX can maybe help you: the `make` function takes all arguments in the query as labelled arguments and returns a structure which contains a `Js.Json.t` value ready to be stringified. Would this suffice, or does it have to be a record type?

You could e.g. do this:

```reason
module MyQuery = [%graphql {|
  mutation ($username: String!, $password: String!) { ... }
|}];


/* In your code somewhere */
let variablesData = MyQuery.make(~username=state.username, ~password=state.password, ())
  |> Js.Json.stringify;
```

In the other direction - the PPX exposes a `parse` function that takes a `Js.Json.t` and returns an `option` containing the typed result of the query. Again - do you really need each of the types of the query, or are you just interested in the typed result? This PPX does some transformations to better map the data better to OCaml types - nullables becomes `option`s, unions and enums become polymorphic variants, you can optionally create records, etc.

The `parse` function corresponds to `convert` in your example above, so you would do:

```reason
let convert = MyQuery.parse;
```

**Comment by grsabreu** [comment]
Hi there!

I need the input and the output types separately to give them to the `mutate` prop function passed by the Apollo HOC in the binding I made for the mutation queries. 

```reason
module CreateMutationWrapper =
       (Query: {type data; type input; type response; let query: GraphQLTag.definitions;}) => {
  /* Args that the Apollo mutate will receive */
  type jsMutationArgs = {. "variables": {. "input": Query.input}};
  /* Props passed directly from the Apollo HOC */
  type props = {. "mutate": jsMutationArgs => Js.Promise.t({. "data": Query.response})};
  let component = ReasonReact.statelessComponent("ApolloWrapper");

  /* Pretty much here, it's basically the same signature of the `parse` function the PPX gives but instead of the named params this receives a Js.t bag */
  let make' = (~mutate: Query.input => Js.Promise.t(Query.response), children) => {
    ...component,
    render: (_self) => children[0](~mutate)
  };
  let make = (children) => {
    let jsComponent =
      ReasonReact.wrapReasonForJs(
        ~component,
        (props: props) => {
          let mutate = (variables: Query.input) => {
            let mutate' = props##mutate;
            Js.Promise.(
              mutate'({"variables": {"input": variables}})
              |> then_((data) => data##data |> resolve)
            )
          };
          make'(~mutate, children)
        }
      );
    let enhanced = graphql(Query.query, jsComponent);
    ReasonReact.wrapJsForReason(~reactClass=enhanced, ~props=Js.Obj.empty(), [||])
  };
};
```

**Comment by mhallin** [comment]
I see. I've had on my todo list to expose the generated type in the module, hopefully I'll get around to it soon. As for variables, I'll need to think about how to best do it.

You seem to need a function like `variables => Js.Promise.t(result)`, so it could either be a record or a `Js.t` object, as long as it eventually can be serialised into a `Js.Json.t`. Am I understanding it correctly?

**Comment by grsabreu** [comment]
Yes, exactly! 
I even tried to look the PPX code to see if I could do it by myself, but I'm still learning and still a bit lost in there haha

**Comment by thangngoc89** [comment]
Hey. I've come across to this exact issue when integrating Apollo Client (the library that React Apollo built on).
 This is what I've got so far 

https://github.com/thangngoc89/reason-apollo

I tried to keep my module signature as general as possible and let the compiler figure out what type is it. But if this PPX could expose the input and output type of the parse function, it would allow me to do more optimizations.

**Comment by mhallin** [comment]
I just pushed version 0.0.4 to OPAM, which contains some improvements to make interop with Apollo a little bit better:

* Query modules now contains a `t` type which is the return value of `parse` - i.e. the type of the decoded query.
* A new `makeWithVariables` function, similar to `make` but taking a single `Js.t` object instead of labelled arguments.
* The PPX can generate the AST for the query instead of the raw source, removing the need for `graphql-tag` or babel post-processing. This support is experimental and might be broken for some queries.

You can read about these at the end of the README: https://github.com/mhallin/graphql_ppx#alternative-querymake-syntax.

Unfortunately, I couldn't easily generate a concrete type for the input variables of a query so the update is not a 100% solution for the problems in this issue. But, if the other improvements sound helpful, please try them out and let me know if you run into problems.

**Comment by grsabreu** [comment]
That is awesome @mhallin, thank you!

**Comment by grsabreu** [comment]
Closing this now since we have the type separated
