### ISSUE TITLE
make arguments are note validated

### ISSUE THREAD

**Issue by Gregoirevda** [mhallin/graphql_ppx#16]
module HeroQuery = [%graphql {|
    query getPokemon($name: String!){
      pokemon(name: $name) {
          id
      }
    }
|}];

let query = HeroQuery.make(~name="Pikachu") /* Pass */
let query = HeroQuery.make() /* Should fail, but compiles */

**Comment by wokalski** [comment]
It’s not a bug. Check the type of the second “bad” query.

**Comment by Gregoirevda** [comment]
`let query = HeroQuery.make(())`
Perfectly working! Thanks
