### ISSUE TITLE
Can't install with newer version of ocaml (4.06.0)

### ISSUE THREAD

**Issue by happylinks** [mhallin/graphql_ppx#17]
In the ocaml file it says:
`available: [ocaml-version = "4.02.3"]`

Can we change this to >= instead? I can make a PR if that is the way to solve it :)

**Comment by wokalski** [comment]
`graphql_ppx` only works with BuckleScript which in turn is only compatible with OCaml `4.02.3`

**Comment by happylinks** [comment]
Ahh, maybe that's the reason I'm having some issues. My global ocaml version is 4.06. Any idea how to downgrade the best way? I'll do some research

**Comment by happylinks** [comment]
https://github.com/BuckleScript/bucklescript/wiki/Installation
`opam switch 4.02.3+buckle-1`
Thanks for the quick response!
