### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by pokorson** [mhallin/graphql_ppx#18]
Hi,

I'm having such error while trying to install package:

```
The following actions will be performed:
  ∗  install graphql_ppx 0.0.3

=-=- Gathering sources =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[graphql_ppx] Archive in cache

=-=- Processing actions -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
[ERROR] The compilation of graphql_ppx failed at "make install".
Processing  1/1: [graphql_ppx: make uninstall]
#=== ERROR while installing graphql_ppx.0.0.3 =================================#
# opam-version 1.2.2
# os           darwin
# command      make install
# path         /Users/pokora/.opam/4.02.3/build/graphql_ppx.0.0.3
# compiler     4.02.3
# exit-code    2
# env-file     /Users/pokora/.opam/4.02.3/build/graphql_ppx.0.0.3/graphql_ppx-31146-58c514.env
# stdout-file  /Users/pokora/.opam/4.02.3/build/graphql_ppx.0.0.3/graphql_ppx-31146-58c514.out
# stderr-file  /Users/pokora/.opam/4.02.3/build/graphql_ppx.0.0.3/graphql_ppx-31146-58c514.err
### stdout ###
# ocamlbuild -use-ocamlfind \
# 		-package ocaml-migrate-parsetree \
# 		-package result \
# 		-package yojson \
# 		-package ppx_tools.metaquot \
# 		-I src \
# 		graphql_ppx.native
### stderr ###
# make: opam-installer: No such file or directory
# make: *** [install] Error 1



=-=- Error report -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=  🐫
The following actions failed
  ∗  install graphql_ppx 0.0.3
No changes have been performed
```

**Comment by mhallin** [comment]
Hello!

What OS are you running, and how did you install OPAM? I've noticed that some distributions of OPAM is missing the `opam-installer` tool for some reason.

See for example [this StackOverflow question](https://stackoverflow.com/questions/45576089/jbuilder-install-fails-no-opam-installer-tool) and [this similar issue](https://github.com/samoht/ocaml-dumpast/issues/4).

**Comment by pokorson** [comment]
I'm running macOs 10.13.2, and opam I think I took their binary with `wget`

**Comment by thangngoc89** [comment]
@pokorson you need to install opam-installer first.

**Comment by mhallin** [comment]
@pokorson I think the official distribution is missing the `opam-installer` binary. If you're otherwise using [Homebrew](https://brew.sh) on your Mac, I suggest installing opam through that.

**Comment by thangngoc89** [comment]
@mhallin I ran into this issue when I installed graphql_ppx too. I followed instructions on ReasonML docs

**Comment by mhallin** [comment]
Upgrading to 0.2.0 should alleviate this issue - graphql_ppx no longer requires an ocaml build toolchain to be installed.
