### ISSUE TITLE
Parsing array result type

### ISSUE THREAD

**Issue by thangngoc89** [mhallin/graphql_ppx#22]
Given this common pattern for an array in GraphQL:

```
type FooConnection {
  edges: [String]!
}
```

This means `edges` always return an array but it could contains 0 or more elements.
The parsed type from graphql_ppx is:

```reason
{
  .
  "edges": array(option(string))
}
```

IMHO, this is incorrect type and it makes it annoying to work with. But still, I can't think of a clever way to express the above GraphQL type in ReasonML

**Comment by mhallin** [comment]
`[String]!` means an array that contains 0 or more elements of strings _or null_.

If your schema instead would use `[String!]!`, graphql_ppx would convert it into `array(string)`.

**Comment by thangngoc89** [comment]
@mhallin Ah. Thank you. I'll update my schema accordingly.
