### ISSUE TITLE
Add .exe extension copy of ppx file on build

### ISSUE THREAD

**Issue by WolfDan** [mhallin/graphql_ppx#25]
Hello,

I'm working on windows with reason-apollo it actually runs the ppx command, but it don't work on windows since it needs to have the .exe extension, I can add it manually but every time that I add a new package or remove one from my project the package is rebuild and the .exe file is gone,

So I hope if is possible to add a copy of the file ppx with .exe extension on release build ^^/

Greetings

**Comment by mhallin** [comment]
The newly released version 0.2.2 copies the binary to both `ppx` and `ppx.exe`, so this _should_ work on Windows now. Could you please confirm this?
