### ISSUE TITLE
GraphqlObjectType __typename

### ISSUE THREAD

**Issue by Coobaha** [mhallin/graphql_ppx#31]
Hi @mhallin, thanks for this project! ❤️ 

I think GraphqlObjectType also allows __typename.

https://github.com/mhallin/graphql_ppx/blob/12be4aec081df6e8e12a81b48369e38195f69d6c/src/graphql_printer.ml#L72

https://graphqlbin.com/v2/7L82Tn (not sure if it is object there) but my local graphql sends it with Objects. 

Currently I am not allowed to use it in my code
```
  16 ┆ renderer(id: $id) {
  17 ┆   label
  18 ┆   __typename
  19 ┆
  20 ┆ }

  Unknown field on type Renderer
```

**Comment by mhallin** [comment]
Thanks for the report! This is now solved in the newly published version 0.2.2.

Note though that you can't have `__typename` on union fields since they are converted into variants rather than objects.
