### ISSUE TITLE
trying to query array of scalars as object results in error

### ISSUE THREAD

**Issue by Coobaha** [mhallin/graphql_ppx#32]
example of query:
```
{
  arrayOfStrings: {
    id
  }
}

```

```
 There's been an error running a preprocessor before the compilation of a file.
  This was the command:

 ./node_modules/graphql_ppx/ppx '/var/folders/c1/v8_9j1yn65dcm4g1ltl9968h0000gn/T/camlppx4cafcc' '/var/folders/c1/v8_9j1yn65dcm4g1ltl9968h0000gn/T/camlppxf84920'
```

**Comment by mhallin** [comment]
Hello!

That syntax has an invalid syntax. Was that the entire message you got from the compiler, or did it say anything else? It should say something like "Invalid token {" on the second line.

The correctly formed query would look something like

```graphql
{
  arrayOfStrings {
    id
  }
}
```

**Comment by Coobaha** [comment]
@mhallin Sorry, you are right! I was typing this example by hand but error is from compiler with correct syntax
```
{
  arrayOfStrings {
    id
  }
}
```

**Comment by Coobaha** [comment]
So instead of saying that this is array of primitives compiler tries to find corresponding array of objects from schema and fails with error above.

**Comment by mhallin** [comment]
Does the compiler say anything else? There's usually a message right before the "We've found a bug for you" line.

**Comment by Coobaha** [comment]
@mhallin 
no,

```

  There's been an error running a preprocessor before the compilation of a file.
  This was the command:

  ./node_modules/graphql_ppx/ppx '/var/folders/c1/v8_9j1yn65dcm4g1ltl9968h0000gn/T/camlppx1272f6' '/var/folders/c1/v8_9j1yn65dcm4g1ltl9968h0000gn/T/camlppxe02017'

```

**Comment by mhallin** [comment]
Alright, I've found the root cause. The error message will be fixed in the next release.
