### ISSUE TITLE
Subscription support

### ISSUE THREAD

**Issue by Gregoirevda** [mhallin/graphql_ppx#33]
Does the ppx has support for Subscriptions?

I added a PR to reason-apollo to bind the Subscription component: https://github.com/apollographql/reason-apollo/pull/96

I'd be glad to help to add support. Shouldn't be much different from a query?

**Comment by mhallin** [comment]
If the JSON responses look the same as queries and mutations, then #36 should be ready to go. Could you please confirm this, I haven't got an easy way to test subscriptions right now.
