### ISSUE TITLE
Validation for (required) query / mutation arguments

### ISSUE THREAD

**Issue by anmonteiro** [mhallin/graphql_ppx#35]
The same way this PPX validates if a queried field is not present in the schema, I think it could validate that a required argument isn't passed to a query or a mutation?

I just ran into this and the server threw a runtime error. I think it could be caught at compile time. Is this on the roadmap?

**Comment by wokalski** [comment]
I think it is. It's in the `Limitations` section of the readme.

**Comment by anmonteiro** [comment]
Thanks for clarifying, I wasn't sure if this is what that bullet point was referring to.

**Comment by johnhaley81** [comment]
👋 this issue hasn't had a lot of activity on it but I was wondering if there was a good place to start to try to fix this? Thanks :)

**Comment by baransu** [comment]
I haven't touched that part of the code but I assume it happens [here](https://github.com/mhallin/graphql_ppx/blob/master/src/bucklescript/output_bucklescript_unifier.ml#L28) for BuckleScript and [here](https://github.com/mhallin/graphql_ppx/blob/master/src/native/output_native_unifier.ml#L26) for Native. It's a really important issue so I hope you will succeed!

**Comment by baransu** [comment]
I have [PR](https://github.com/baransu/graphql_ppx_re/pull/19) to [baransu/graphql_ppx_re](https://github.com/baransu/graphql_ppx_re) implementing such check. If you're interested you can take a look :)
