### ISSUE TITLE
specify record type with @bsRecord

### ISSUE THREAD

**Issue by svoynow** [mhallin/graphql_ppx#37]
Is this currently possible?

**Comment by anmonteiro** [comment]
Yep, here's an example: https://github.com/anmonteiro/reason-graphql-fullstack/blob/8b8e904542252adacd5bb28f3c5d66fe2486bf20/src/client/App.re#L61

**Comment by mhallin** [comment]
To clarify; it's _not_ possible to specify _which_ type you want `@bsRecord` to pick, if you e.g. want a record from a different module, or disambiguate between records with overlapping fields. I'm working on a big update that hopefully will address this issue.

**Comment by svoynow** [comment]
yeah, I was stuck on the idea of being able to provide an argument to the directive, but just creating a type alias for whatever the field name happens to be works fine for my use-case
