### ISSUE TITLE
Skip/Include directives are parsed incorrectly

### ISSUE THREAD

**Issue by Coobaha** [mhallin/graphql_ppx#40]
Hi!

https://github.com/mhallin/graphql_ppx/blob/fd7f665a28aad6caba74ec48ece0639062bcc267/tests/types/skipDirectives.re#L1-L14

Using this directives results in a runtime error because parse code assumes that field should be null or correct type
```
        var match$7 = value$1["committedFields"];
        var tmp$3;
        if (match$7 !== undefined) {
          var match$8 = Js_json.decodeNull(match$7);
          ...
        } else {
          throw [
                Graphql_error$2,
                "Field committedFields on type Module is missing"
              ];
        }
```

**Comment by mhallin** [comment]
Thanks for this report, the newly released version 0.2.5 fixes this issue.
