### ISSUE TITLE
schema.json not found

### ISSUE THREAD

**Issue by revskill10** [mhallin/graphql_ppx#50]
I have a `schema.json` at root of project using `apollo schema:download`.
When running `npm start`, i got error:
```
Fatal error: exception Failure("graphql_ppx/ppx\\ -schema=schema.json not found when resolving ppx-flags")
```

My `bsconfig.json`:
```
"bs-dependencies": [
    "reason-react",
    "reason-apollo",
    "@glennsl/bs-json"
  ],
  "ppx-flags": [
    "graphql_ppx/ppx\\ -schema=schema.json"
  ],
```

**Comment by mhallin** [comment]
Are you using bs-platform 4.0.2? In that case, you need remove `\\` from the flags. I was waiting for the release to update the documentation but I must've missed it, sorry.

**Comment by revskill10** [comment]
@mhallin yes, i'm using bs-platform 4.0.2. Even without `\\`, it still got error (not above error). But i got thing to work through the `yarn send-introspection-query` though. Better documentation though on how to use custom schema name.
Second question: How to use multiple graphql schemas in one project ?
