### ISSUE TITLE
Error: Unbound value json_of_Datetime

### ISSUE THREAD

**Issue by rauanmayemir** [mhallin/graphql_ppx#51]
Since the upgrade to `bucklescript@4.0.3` and `graphql_ppx@0.2.6` all scalar types stopped working.

Compiler crashes with an error like `The value json_of_ScalarType can't be found`.

**Comment by rauanmayemir** [comment]
I'm guessing `0.2.6` brought a regression, because pinning to `graphql_ppx@0.2.4` helps.

**Comment by mhallin** [comment]
It unfortunately sounds like custom scalar encoding might be broken in the latest release, yes. I'll try to get a fix released as soon as possible.

**Comment by thangngoc89** [comment]
I thought this is a feature. Haha. I have a lot of scala and the previous verisons, I have to cast the type with `%identity` hack. this time, I just provide a function in scope

**Comment by rauanmayemir** [comment]
Yeah, I thought of adding those functions myself, but was unsure.

**Comment by mhallin** [comment]
This issue is fixed in 0.2.7.

I suggest using `Js.Json.string` or whatever function you want to produce a `Js.Json.t` out of your native type, rather than relying on the `%identity` hack though.
