### ISSUE TITLE
Parsing error when using fragments

### ISSUE THREAD

**Issue by tmattio** [mhallin/graphql_ppx#52]
I am trying to build a query with fragments, it looks like this:

```
module Fragments = [%graphql
  {|
    fragment documentFields on Document {
      sourceText
    }
  |}
];

module GetDataset = [%graphql
  {|
    query dataset($owner: String!, $name: String!) {
      dataset(name: $name, owner: $owner) {
        name
        dataType
        datapoints(first: 100) {
          edges {
            node {
              ...Fragments.DocumentFields @bsField(name: "document")
            }
          }
        }
      }
    }
  |}
];
```

Unfortunately, running this yields a `GraphQLError: Syntax Error: Cannot parse the unexpected character ".".`

Am I doing something wrong with the query?

**Comment by tmattio** [comment]
@mhallin Thanks for the quick answer!
Unfortunately, upgrading to 0.2.7 does not fix the error :/

**Comment by mhallin** [comment]
That's strange. Have you run `bsb -clean-world -make-world` to make sure that everything is recompiled with the new ppx?

**Comment by tmattio** [comment]
I didn't, cleaning the build solves the issue! Thanks a lot :)
