### ISSUE TITLE
schema change is not detected

### ISSUE THREAD

**Issue by bsr203** [mhallin/graphql_ppx#54]
Hi.
I use latest version, and saw caching introduced with it. I noticed that when the server schema changes (and update at client through yarn send-introspection-query ..) "bsb -make-world" doesn't report any graphql error. If I change the query (within  [%graphql .... |}];), it triggers error. As if the ppx triggers only when the graphql usage changes. Not a big deal, but wonder a way to force it when schema changes during a build or not in watch mode.

Thanks.
bsr

**Comment by thangngoc89** [comment]
you need to run bsb -clean-world whenever your schema changed

**Comment by bsr203** [comment]
thanks.
