### ISSUE TITLE
@bsField is showing up in query output

### ISSUE THREAD

**Issue by alxlu** [mhallin/graphql_ppx#58]
When I create a fragment
```reasonml
module Fragment = [%graphql
  {|
    fragment testFragment on Testing {
        item
    }
    |}
];
```

and then I use it in another query

```reasonml
module Query = [%graphql
  {|
  query getAll {
    testing {
       ...Fragment.TestFragment @bsField(name: "testing")
    }
  }
     
|}
];

```

The output includes the `@bsField(name: "testing")`:

```graphql
query getAll {
    testing {
      ...testFragment @bsField(name: "testing")
   }
}


fragment testFragment on Testing {
  item
}
```

This is on "graphql_ppx@0.2.7"

**Comment by alxlu** [comment]
nvm... I think I may be misunderstanding what `@bsField` is supposed to do. Removing it completely seems to work

**Comment by MoOx** [comment]
@mhallin I am facing this "bug" (not sure if that a pebcak issue or not) where I see `@bsField` in the javascript created by bs.
What can I do to have it gone (I understand this is something related to this ppx only? I am still new to graphql)?
Because Apollo doesn't seems to like this directive :)

**Comment by Emilios1995** [comment]
@mhallin I'm sure this is a bug.
It also happens in `0.2.8`
This is my query: 
```
  module GQL = [%graphql
    {|
      query sharePropertyPage($id: ID!) {
        property(id: $id)  @bsDecoder(fn: "Property.decode") {
        images {
            id
            key
          }
        ...Fragments.PropertyBasicInfo @bsField(name: "basicInfo")
        }
      }
    |}
  ];
```
And `@bsField(name: "basicInfo")` is showing up in the output. 
Can we reopen this?

**Comment by Emilios1995** [comment]
Isn't the solution just to add `bsField` in this line?
https://github.com/mhallin/graphql_ppx/blob/0b1ce89164fdbd09b9e5532b8589d1f1da1f319e/src/base/graphql_printer.ml#L53
