### ISSUE TITLE
Need bsField name when spreading fragments

### ISSUE THREAD

**Issue by tmattio** [mhallin/graphql_ppx#63]
Migrating from 0.2.7 from 0.2.8 creates errors when sprearding fragments:

```
  80 ┆ edges @bsRecord {
  81 ┆   node @bsRecord {
  82 ┆     ...Document
  83 ┆   }
  84 ┆ }

  You must use @bsField(name: "fieldName") to use fragment spreads
```

This is really strange because I've seen a test for this:
```
module ExternalFragmentQuery = [%graphql {|
  fragment Fragment on VariousScalars @bsRecord {
    string
    int
  }
   {
    variousScalars {
      ...Fragment
    }
  }
|}];
```

Not sure what is the difference between my code and the test.

**Comment by mhallin** [comment]
This sounds like a regression in 0.2.8 unfortunately :( I'll add tests for fragments in interfaces.

**Comment by tmattio** [comment]
Hi @mhallin :)

Any luck on this? I am currently blocked because I need to use inline fragment (they must be parametrized), but my types are interfaces :/

**Comment by baransu** [comment]
@tmattio I'll try to look into it over the weekend but no promised are made 🙂

**Comment by elnygren** [comment]
Temp dirty runtime hotfix for anyone struggling with this...

```reason
let bsFieldFix =
  Js.String.replaceByRe(
    Js_re.fromStringWithFlags("@bsField(.*)", ~flags="g"),
    "",
  );

module GQL = ...actual graphql query...

module GQLFix = {
    include GQL;
    let query = bsFieldFix(GQL.query);
    let ppx_printed_query = bsFieldFix(GQL.ppx_printed_query);
  };

  module Query = ReasonApollo.CreateQuery(GQLFix);
```

:(
