### ISSUE TITLE
Type of Input Object not compiling

### ISSUE THREAD

**Issue by jcdoig** [mhallin/graphql_ppx#78]
I tried the solution mentioned in issue 38 to type a graphql object input. However it does not compile in bs-platform 4.0.18 It complains that there is no Js_unsafe module. The Js_unsafe module was merged with the Js module back in Nov 2018. The compiler complains that Js_unsafe.unsafe_downgrade function is missing

**Comment by baransu** [comment]
What version of `graphql_ppx` are you using?

**Comment by jcdoig** [comment]
My bad, I was using an outdated version.
