### ISSUE TITLE
Ast mapper version is not compatible with bs-platform v7

### ISSUE THREAD

**Issue by Sydney-o9** [mhallin/graphql_ppx#96]
@baransu @anmonteiro I've tried to use `graphql_ppx` with the most recent bs-platform v7 and they are not compatible.

`bsb` output is:

```
Failure("Ast_mapper: OCaml version mismatch or malformed input")
  Error while running external preprocessor
Command line: /Users/xxx/Sandbox/reasonml/xxxx-frontend/node_modules/graphql_ppx/ppx '/var/folders/l5/yw1pj_850wl8zb3nyrzkp19w0000gn/T/camlppx664bf5' '/var/folders/l5/yw1pj_850wl8zb3nyrzkp19w0000gn/T/camlppxfde9a1'
```

`package.json` is:

```
  "devDependencies": {
    "bs-platform": "7.3.2"
  },
  "dependencies": {
    "graphql_ppx": "^0.2.8"
  }
```

This issue seemed to [have happened previously with bs-platform v6](https://github.com/mhallin/graphql_ppx/issues/77) - support for Bucklescript 6.x [fixed it](https://github.com/reasonml-community/graphql-ppx/issues/6).

Any ideas if we can get `graphql_ppx` to work with `bs-platform` v7?

**Comment by baransu** [comment]
This repository is deprecated. Please use @reason-community/graphql-ppx

**Comment by Sydney-o9** [comment]
Thank you @baransu - I have now posted on `@reason-community/graphql-ppx` https://github.com/reasonml-community/graphql-ppx/issues/210
